export type H5RuntimeBinding = {
  key: string;
  selector: string;
  label: string;
  href: string | null;
  mode: 'customer_service' | 'link' | null;
};

/**
 * Browser-only runtime injected into published H5 pages. It intentionally owns
 * no private configuration: the handoff endpoint returns only the verified
 * public customer-service endpoint and a one-time source handoff id.
 */
export function renderH5Runtime(bindings: H5RuntimeBinding[]): string {
  return String.raw`(function(){
const bindings=${JSON.stringify(bindings)};
const storageKey='site-h5-support-visitor-v1';
let active=null,refreshTimer=null,socket=null,heartbeat=null;
function emit(type,detail){window.dispatchEvent(new CustomEvent(type,{detail:detail}));}
function id(){const a='ABCDEFGHIJKLMNOPQRSTUVWXYZ',n='0123456789',v=[];for(let i=0;i<3;i++)v.push(a[Math.floor(Math.random()*a.length)]);for(let i=0;i<3;i++)v.push(n[Math.floor(Math.random()*n.length)]);return v.sort(function(){return Math.random()-.5}).join('');}
function identity(){try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved&&typeof saved.visitorId==='string'&&saved.expiresAt>Date.now())return saved;}catch(_){}const next={visitorId:id(),accessToken:null,expiresAt:Date.now()+86400000};save(next);return next;}
function save(value){try{localStorage.setItem(storageKey,JSON.stringify(value));}catch(_){}return value;}
function request(url,init){return fetch(url,Object.assign({cache:'no-store',credentials:'omit',mode:'cors',headers:{Accept:'application/json'}},init||{})).then(async function(response){const body=await response.json().catch(function(){return null;});if(!response.ok)throw new Error(body&&body.error&&body.error.message||'无法连接客服，请稍后重试。');return body;});}
function clientUrl(path){const visitor=identity(),url=new URL(active.connection.clientApiUrl.replace(/\/$/, '')+path);url.searchParams.set('visitorId',visitor.visitorId);if(visitor.accessToken)url.searchParams.set('visitorToken',visitor.accessToken);return url.toString();}
function clientBody(value){const visitor=identity();return Object.assign({visitorId:visitor.visitorId},visitor.accessToken?{visitorToken:visitor.accessToken}:{},value);}
function stylesheet(){if(document.getElementById('site-h5-support-style'))return;const style=document.createElement('style');style.id='site-h5-support-style';style.textContent=':root{--site-h5-chat-brand:var(--brand,#e85d75);--site-h5-chat-surface:#fff;--site-h5-chat-text:#17171b;--site-h5-chat-muted:#777} .site-h5-chat{position:fixed;inset:0;z-index:2147483000;display:grid;place-items:end center;padding:16px;background:rgba(12,10,14,.5);backdrop-filter:blur(8px)}.site-h5-chat[hidden]{display:none}.site-h5-chat__panel{display:grid;width:min(100%,460px);height:min(76dvh,680px);grid-template-rows:auto 1fr auto;overflow:hidden;border-radius:22px;background:var(--site-h5-chat-surface);color:var(--site-h5-chat-text);box-shadow:0 24px 70px rgba(0,0,0,.35)}.site-h5-chat__head{display:flex;align-items:center;gap:10px;padding:15px 16px;border-bottom:1px solid #ececf0}.site-h5-chat__head strong{font:700 15px/1.2 system-ui,sans-serif}.site-h5-chat__head small{display:block;margin-top:3px;color:var(--site-h5-chat-muted);font:12px/1.2 system-ui,sans-serif}.site-h5-chat__close{margin-left:auto;border:0;background:transparent;color:inherit;font:24px/1 system-ui;cursor:pointer}.site-h5-chat__messages{display:flex;min-height:0;flex-direction:column;gap:8px;overflow:auto;padding:16px;background:#faf9fb}.site-h5-chat__message{max-width:78%;padding:9px 12px;border-radius:15px;font:14px/1.45 system-ui,sans-serif;white-space:pre-wrap;word-break:break-word}.site-h5-chat__message--agent{align-self:flex-start;background:#ececf0;border-bottom-left-radius:4px}.site-h5-chat__message--customer{align-self:flex-end;background:var(--site-h5-chat-brand);color:#fff;border-bottom-right-radius:4px}.site-h5-chat__state{margin:auto;color:var(--site-h5-chat-muted);font:14px/1.45 system-ui,sans-serif;text-align:center}.site-h5-chat__form{display:flex;gap:8px;padding:11px;border-top:1px solid #ececf0}.site-h5-chat__form input{min-width:0;flex:1;border:1px solid #dedee5;border-radius:999px;padding:11px 13px;font:14px system-ui}.site-h5-chat__form button{border:0;border-radius:999px;padding:0 16px;background:var(--site-h5-chat-brand);color:#fff;font:700 13px system-ui;cursor:pointer}.site-h5-chat__form button:disabled{opacity:.55;cursor:wait}';document.head.appendChild(style);}
function mount(){stylesheet();let host=document.querySelector('[data-site-chat-root]');if(!host){host=document.createElement('section');host.dataset.siteChatRoot='';document.body.appendChild(host);}host.classList.add('site-h5-chat');host.hidden=true;host.setAttribute('role','dialog');host.setAttribute('aria-modal','true');host.innerHTML='<div class="site-h5-chat__panel"><header class="site-h5-chat__head"><div><strong data-chat-name>正在连接顾问</strong><small data-chat-status>请稍候…</small></div><button class="site-h5-chat__close" type="button" aria-label="关闭聊天">×</button></header><div class="site-h5-chat__messages" role="log" aria-live="polite"></div><form class="site-h5-chat__form"><input aria-label="输入消息" autocomplete="off" placeholder="输入消息…" disabled><button type="submit" disabled>发送</button></form></div>';host.querySelector('.site-h5-chat__close').addEventListener('click',close);host.querySelector('form').addEventListener('submit',send);return host;}
function ui(){return document.querySelector('[data-site-chat-root]');}
function state(message){const root=ui();if(!root)return;const list=root.querySelector('.site-h5-chat__messages');list.innerHTML='';const node=document.createElement('p');node.className='site-h5-chat__state';node.textContent=message;list.appendChild(node);root.querySelector('[data-chat-status]').textContent=message;}
function render(){const root=ui(),conversation=active&&active.conversation;if(!root||!conversation)return;root.querySelector('[data-chat-name]').textContent=conversation.agentName||'在线顾问';root.querySelector('[data-chat-status]').textContent=conversation.status==='closed'?'会话已结束':'在线';const list=root.querySelector('.site-h5-chat__messages');list.innerHTML='';(conversation.messages||[]).forEach(function(message){if(!message.body)return;const node=document.createElement('div');node.className='site-h5-chat__message site-h5-chat__message--'+(message.direction==='agent'?'agent':'customer');node.textContent=message.body;list.appendChild(node);});list.scrollTop=list.scrollHeight;const input=root.querySelector('input'),button=root.querySelector('button[type="submit"]');const disabled=conversation.status==='closed';input.disabled=disabled;button.disabled=disabled;}
async function refresh(){if(!active)return;const payload=await request(clientUrl('/conversations/'+encodeURIComponent(active.conversation.id)));if(payload&&payload.conversation){active.conversation=payload.conversation;render();}}
function openSocket(){if(!active||!active.connection.realtimeUrl||typeof WebSocket==='undefined')return;const visitor=identity(),url=new URL(active.connection.realtimeUrl);url.searchParams.set('visitorId',visitor.visitorId);if(visitor.accessToken)url.searchParams.set('visitorToken',visitor.accessToken);try{socket=new WebSocket(url.toString());socket.addEventListener('message',function(event){try{const data=JSON.parse(String(event.data));if(data&&data.conversationId===active.conversation.id)void refresh();}catch(_){}});socket.addEventListener('open',function(){heartbeat=window.setInterval(function(){if(socket&&socket.readyState===WebSocket.OPEN)socket.send('ping');},60000);});socket.addEventListener('close',function(){if(heartbeat)window.clearInterval(heartbeat);heartbeat=null;socket=null;});}catch(_){}}
function stopLive(){if(refreshTimer)window.clearInterval(refreshTimer);refreshTimer=null;if(heartbeat)window.clearInterval(heartbeat);heartbeat=null;if(socket)socket.close();socket=null;}
function close(){stopLive();active=null;const root=ui();if(root)root.hidden=true;emit('site:h5-support:closed',{});}
async function open(binding){const root=mount();root.hidden=false;state('正在为您接入顾问…');emit('site:h5-support:opening',{ctaKey:binding.key});try{const handoff=await fetch(binding.href,{headers:{Accept:'application/json'},cache:'no-store'}).then(async function(response){const value=await response.json().catch(function(){return null;});if(!response.ok||!value)throw new Error(value&&value.error&&value.error.message||'该咨询入口暂不可用。');return value;});if(handoff.mode!=='customer_service')throw new Error('该咨询入口暂不可用。');active={connection:handoff.connection,conversation:null};const created=await request(active.connection.clientApiUrl.replace(/\/$/,'')+'/conversations',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(clientBody({sourceHandoffId:handoff.handoffId,product:{id:handoff.product.id}}))});if(created&&typeof created.visitorToken==='string'){const visitor=identity();save(Object.assign({},visitor,{accessToken:created.visitorToken}));}if(!created||!created.conversation)throw new Error('未能建立会话，请重试。');active.conversation=created.conversation;if(active.conversation.status==='waiting')throw new Error('当前暂无可用顾问，请稍后重试。');render();refreshTimer=window.setInterval(function(){void refresh().catch(function(){});},15000);openSocket();emit('site:h5-support:connected',{ctaKey:binding.key,conversation:active.conversation});}catch(error){state(error instanceof Error?error.message:'无法连接客服，请稍后重试。');emit('site:h5-support:error',{ctaKey:binding.key,error:String(error)});}}
async function send(event){event.preventDefault();if(!active||!active.conversation)return;const root=ui(),input=root.querySelector('input'),button=root.querySelector('button[type="submit"]'),body=input.value.trim();if(!body)return;input.disabled=true;button.disabled=true;try{await request(active.connection.clientApiUrl.replace(/\/$/,'')+'/conversations/'+encodeURIComponent(active.conversation.id)+'/messages',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify(clientBody({clientMessageId:crypto.randomUUID?crypto.randomUUID():String(Date.now()),body:body}))});input.value='';await refresh();}catch(error){root.querySelector('[data-chat-status]').textContent=error instanceof Error?error.message:'发送失败，请重试。';}finally{if(active&&active.conversation&&active.conversation.status!=='closed'){input.disabled=false;button.disabled=false;input.focus();}}}
function apply(){bindings.forEach(function(binding){document.querySelectorAll(binding.selector).forEach(function(element){if(binding.label)element.textContent=binding.label;if(!binding.href||element.dataset.siteCtaBound)return;element.dataset.siteCtaBound='1';element.addEventListener('click',function(event){event.preventDefault();if(binding.mode==='customer_service')void open(binding);else window.location.href=binding.href;},{capture:true});});});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();
})();`;
}
