export const SYSTEM_UI = {
  all: 'All',
  attachment: 'Attachment',
  back: 'Back',
  clear: 'Clear',
  dismiss: 'Dismiss',
  install: 'Install',
  loadEarlier: 'Load earlier',
  loading: 'Loading…',
  message: 'Message',
  messageFailed: 'Message could not be sent.',
  more: 'More',
  noResults: 'No results',
  notFound: 'Not found',
  read: 'Read',
  retry: 'Retry',
  search: 'Search',
  send: 'Send',
  sending: 'Sending',
  sent: 'Sent',
  unavailable: 'Unavailable',
  yesterday: 'Yesterday',
} as const;
