export const SYSTEM_UI = {
  addToHomeScreen: 'Add to Home Screen',
  all: 'All',
  attachment: 'Attachment',
  back: 'Back',
  clear: 'Clear',
  continue: 'Continue',
  conversationClosed: 'Conversation closed',
  dismiss: 'Dismiss',
  enableNotifications: 'Enable notifications',
  install: 'Install',
  loadEarlier: 'Load earlier',
  loading: 'Loading…',
  message: 'Message',
  messageFailed: 'Failed',
  more: 'More',
  notificationsBlocked: 'Notifications blocked',
  notificationsEnabled: 'Notifications enabled',
  noSupport: 'No support available',
  noResults: 'No results',
  notFound: 'Not found',
  read: 'Read',
  retry: 'Retry',
  search: 'Search',
  send: 'Send',
  sending: 'Sending',
  sent: 'Sent',
  temporarilyUnavailable: 'Temporarily unavailable',
  unavailable: 'Unavailable',
  unread: 'unread',
  waitingForSupport: 'Waiting for customer service',
  yesterday: 'Yesterday',
} as const;
